apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: cloudguard-retrain-
spec:
  serviceAccountName: workflow-runner
  entrypoint: training-pipeline
  templates:
  - name: training-pipeline
    steps:
    - - name: train-model
        template: trainer

  - name: trainer
    container:
      image: ghcr.io/surabhisahay03/cloudguard-trainer:latest
      imagePullPolicy: Always
      command: ["python", "train.py"]
      env:
        - name: LOG_BUCKET_NAME
          value: "cloudguard-sentinel-datalogs-surabhi"
        - name: MLFLOW_TRACKING_URI
          # Format: http://<SERVICE_NAME>.<NAMESPACE>.svc.cluster.local:5000
          value: "http://mlflow-cloudguard.mlflow.svc.cluster.local:5000"
